### ISSUE TITLE
Reporte de entrevista 

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-s-b-j#1]
[REPORTE DE ENTREVISTA.pdf](https://github.com/user-attachments/files/17563581/REPORTE.DE.ENTREVISTA.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
Excelente trabajo, obtuvieron 28% de acuerdo a la rúbrica.

**Comment by josealfredo79** [comment]
bien hecho y revisado..
